project: 
  type: website

website:
  title: "Cours P8 2024"
  navbar:
    background: primary
    search: true
    left:
      - text: "Introduction"
        href: O1_intro.qmd
      - text: "Jour1"
        href: 02_jour1.qmd
    right:
      - icon: fa-github
        href: https://github.com/beababa/coursP8

format: 
  html:
    theme: yeti
    number_sections: yes
    exclude: [data-raw, data]
    css: styles.css
    toc : true