project: 
  type: website

website:
  title: "Cours P8 2024"
  navbar:
    background: primary
    search: true
    left:
      - text: "Introduction |"
        href: 01_intro.qmd
      - text: " Première carte |"
        href: 02_carte1.qmd
      - text: " Bureaux de vote |"
        href: 03_bv.qmd
      - text: " Rues et bâtiments |"
        href: 04_rueBat.qmd
    right:
      - icon: github
        href: https://github.com/beababa/coursP8

format: 
  html:
    theme: yeti
    number_sections: yes
    toc: true