project: 
  type: website

website:
  title: "Cours P8 2026 - Plan marche"
  navbar:
    background: primary
    search: true
    left:
      - text: "Introduction |"
        href: 01_intro.qmd
      - text: " Plugin JOSM |"
        href: 02_jour1.qmd
      - text: " Plugin QGIS |"
        href: 03_jour2.qmd
      - text: " Rectifications "
        href: 04_jour3.qmd
    right:
      - icon: github
        href: https://github.com/beababa/coursP8

format: 
  html:
    theme: yeti
    number_sections: yes
    toc: true