---
title: "Utilisation mapvotr pour Bondy"
author: "BMaranget"
date: "2/08/2023"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Objectif

Utiliser le package pour Bondy

```{r}
library(mapvotr)
library(sqldf)
library(sf)
data <- read.csv("data/table-adresses-reu.csv", nrows = -10)
str(data)
data <- read.csv.sql("data/table-adresses-reu.csv", sql = "select * from file where code_commune_ref = '93140' ")
```


```{r}
st_layers(data/vote.gpkg)
sf::st_layers(data/vote.gpkg)
getwd()
bv <- st_read
```



# autres données : résultat élections


```{r}
res <- read.csv("data/res.csv", dec =".")
# jointure
autocad
data <- merge(autocad, res, by.x= "numBureau", by.y="Code.du.b.vote")
st_write(data, "data/vote.gpkg", "resultat")
```


pb sur logement.gpkg

```{r}
st_layers("data/logement.gpkg")
RPLS <- st_read("data/logement.gpkg", "RPLS")
quartiers <- st_read("data/logement.gpkg", "quartiersBailleurs")
st_write(RPLS, "data/logement.gpkg", "RPLS")
st_write(quartiers, "data/logement.gpkg", "quartier")
```

carte des attributions

```{r}
attribBureau <- read.csv("data/attribBureau.csv")
# jointure avec zones 
library(sf)
zone <- st_read("data/vote.gpkg", "bureauPolyZone")
joint1 <- merge(zone, attribBureau, by.x="numBureau", "bureau1")
joint2 <- merge(zone, attribBureau, by.x="numBureau", "bureau2")
joint1 <- joint1  [,-4]
joint2 <- joint2 [,-4]
joint <- rbind(joint1, joint2)
```


```{r}
library(mapsf)
png("img/attribBureau.png", res=200, width = 1200, height = 1200)
mf_map(joint, type = "typo", var="prénom", border=NA, leg_pos = NA)
mf_label(joint, "prénom", halo =T, cex = 0.7, overlap=F)
mf_layout("attribution des zones", credits = "Cours P8\naoût 2023")
dev.off()
st_write(joint,"data/vote.gpkg", "bureauPolyZone", delete_layer=T)
```