---
title: "Une saisie exhaustive ?"
author: "BMaranget"
date: "27/08/2023"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Objet

Afin de vérifier la saisie, on part sur un essai de cartographie électorale, liant résultats et logements sociaux.


# Courte vérification

## Extractions avec overpass turbo

Quels tags allons nous utiliser ?

## CARTE 5 : carte pour une nouvelle saisie

Reste-t-il beaucoup à saisir ?
En fonction, nouveau cycle uniquement sur les périmètres


# données élections par bureau

https://www.data.gouv.fr/fr/pages/donnees-des-elections/

On utilise l'explorateur du site et on conserve uniquement les tx d'abstentions et le vote LEPEN pour Bondy.

- fichier de résultat (data/res.cvs)

On effectue ensuite une jointure.

Le résultat est stocké dans la couche résultat du vote.gpkg


# autres

- extractions OSM : bureaux de vote, logements sociaux

Dénombrer le nombre de logements sociaux par périmètre de votants

# Deux propositions de carte


## première carte : tx d'abstention et logements sociaux

Faire une carte affichant ce nombre et le taux d'abstention.

## deuxième carte : vote LE PEN et logements sociaux

Idem


# Conclusion

La saisie est-elle terminée ?

